### ISSUE TITLE
Navigate the tab always reload the page content

### ISSUE THREAD

**Issue by cnakh** [Maxeh/react-native-tabbar-bottom#1]
Your package is very nice, but when I use it in my App it always refresh/reload the content when navigate the tab.

How can I prevent reload page when navigate the tab?

**Comment by Maxeh** [comment]
Hey, thanks. I'm not entirely sure if this is possible with my package. But you could have a look at the TabNavigator of react-navigation or at the Tabs of native-base instead. You might need to integrate the badge icon there yourself, but you could use the badge-icon package for that.
