### ISSUE TITLE
iPhone X Support

### ISSUE THREAD

**Issue by ror-y** [Maxeh/react-native-tabbar-bottom#2]
How can we get around the issue presented by iPhone X, in which the bottom bar obscures the footer?

![screen shot 2018-01-10 at 11 18 07](https://user-images.githubusercontent.com/10364894/34770149-fd06122c-f5f7-11e7-9ee9-f408128467e0.png)

**Comment by Maxeh** [comment]
Hm, I guess the package must be updated then. There needs to be a check for the iPhoneX like described [here](https://aaronpresley.com/determine-if-on-iphone-x-in-react-native/) and then the height of the tabbar has to be adjusted. This cannot be done with props yet. 

Feel free to create a pull request, I currently do not have time to work on this.

**Comment by ror-y** [comment]
We used https://www.npmjs.com/package/react-native-iphone-x-helper to resolve it

**Comment by Maxeh** [comment]
And then you simply changed the styles in your app?

**Comment by ror-y** [comment]
Yeah I gave the app container `paddingBottom: isIphoneX() ? 25 : 0`. Not the prettiest fix but it works.

**Comment by Maxeh** [comment]
Ok, great to hear that 👍
