### ISSUE TITLE
Add image as an Icon

### ISSUE THREAD

**Issue by kalyanijamunkar10** [Maxeh/react-native-tabbar-bottom#3]
I want image to add as an Icon but i haven't found any solution for it.
Tell me if there is any attribute to add image as an Icon.

**Comment by Maxeh** [comment]
Hey, that is not possible. You have to use an Icon from the ionicon set.

**Comment by Tess-welhazi** [comment]
@Maxeh I really need to use ones from other sets and i can see you have the tff files of all the other standard libraries in the assets folder. 
Is there a way to change it into say, MaterialIcons?

![image](https://user-images.githubusercontent.com/20952652/36783788-77cd1572-1c7d-11e8-8eeb-890f0360aa2d.png)

**Comment by Maxeh** [comment]
Well the package uses Icon component from native base. It uses Ionicon by default. But I think that this can be changed by the right configuration of native base, but Im not sure though. 

You could have a look at this discussion: [LINK](http://discuss.nativebase.io/t/where-to-get-the-list-of-icon-names-used-in-native-base/37/7). They say something about changing the iconFamily. Maybe this helps, you would need to fork the project then and change the iconFamily according to your needs.
