### ISSUE TITLE
OnPress 

### ISSUE THREAD

**Issue by rincethomas** [Maxeh/react-native-tabbar-bottom#9]
Hi,
  How to implement onpress event ?. When i click the icon on bottom bar, i want to navigate to the corresponding screen. How to do that ?.

**Comment by Maxeh** [comment]
The onPress is implemented with the stateFunc. Have a look at the example code.

```
stateFunc={(tab) => {
            this.setState({page: tab.page})
            //this.props.navigation.setParams({tabTitle: tab.title})
          }}
```

**Comment by rincethomas** [comment]
I am using react-navigation. 
{this.state.page === "HomeScreen" && <MyComp navigation={this.props.navigation}>Screen1</MyComp>}
In the above code, what is ''MyComp'' ?.

**Comment by rincethomas** [comment]
Thanks....
